const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'src', 'components', 'primitives');

const files = {
  'ScrollArea.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst ScrollArea = React.forwardRef(({ className, children, ...props }, ref) => (\n  <div ref={ref} className={cn("relative overflow-auto custom-scrollbar", className)} {...props}>\n    {children}\n  </div>\n));\nScrollArea.displayName = "ScrollArea";\nexport { ScrollArea };`,

  'DropdownMenu.jsx': `import React, { useState } from 'react';\nimport { cn } from '../../utils';\nimport { motion, AnimatePresence } from 'framer-motion';\n\nconst DropdownMenu = ({ trigger, children, className }) => {\n  const [open, setOpen] = useState(false);\n  return (\n    <div className={cn("relative inline-block", className)}>\n      <div onClick={() => setOpen(!open)}>{trigger}</div>\n      <AnimatePresence>\n        {open && (\n          <motion.div initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }} className="absolute top-full left-0 mt-2 min-w-[200px] border border-border bg-base-900 z-50 flex flex-col p-1">\n            {children}\n          </motion.div>\n        )}\n      </AnimatePresence>\n    </div>\n  );\n};\nexport { DropdownMenu };`,

  'HoverCard.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst HoverCard = ({ trigger, children, className }) => (\n  <div className={cn("group relative inline-block", className)}>\n    {trigger}\n    <div className="absolute top-full left-1/2 -translate-x-1/2 mt-2 w-64 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-opacity z-50 border border-border bg-base-900 p-4 shadow-2xl">\n      {children}\n    </div>\n  </div>\n);\nexport { HoverCard };`,

  'AlertDialog.jsx': `import React from 'react';\nimport { cn } from '../../utils';\nimport { motion, AnimatePresence } from 'framer-motion';\nimport { createPortal } from 'react-dom';\n\nconst AlertDialog = ({ isOpen, title, description, onCancel, onConfirm }) => {\n  if (typeof document === 'undefined') return null;\n  return createPortal(\n    <AnimatePresence>\n      {isOpen && (\n        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">\n          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-base-900/80 backdrop-blur-sm" />\n          <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }} className="relative bg-base-900 border-2 border-red-900 p-6 w-full max-w-md shadow-2xl">\n            <h2 className="font-serif text-2xl text-red-400 mb-2">{title}</h2>\n            <p className="text-text-secondary text-sm mb-8 font-light">{description}</p>\n            <div className="flex justify-end gap-4">\n              <button onClick={onCancel} className="px-4 py-2 text-sm text-text-secondary hover:text-text-primary uppercase font-mono tracking-widest">Cancel</button>\n              <button onClick={onConfirm} className="px-4 py-2 text-sm bg-red-900/50 text-red-400 border border-red-900 hover:bg-red-900/80 uppercase font-mono tracking-widest">Confirm</button>\n            </div>\n          </motion.div>\n        </div>\n      )}\n    </AnimatePresence>,\n    document.body\n  );\n};\nexport { AlertDialog };`,

  'Calendar.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst Calendar = ({ className, ...props }) => (\n  <div className={cn("p-4 border border-border bg-base-900 inline-block", className)} {...props}>\n    <div className="font-mono text-sm text-center mb-4 uppercase text-accent tracking-widest">September 2026</div>\n    <div className="grid grid-cols-7 gap-2 text-center text-xs font-mono text-text-secondary mb-2">\n      <div>Su</div><div>Mo</div><div>Tu</div><div>We</div><div>Th</div><div>Fr</div><div>Sa</div>\n    </div>\n    <div className="grid grid-cols-7 gap-2 text-sm font-light">\n      {Array.from({length: 30}).map((_, i) => (\n        <button key={i} className={cn("h-8 w-8 flex items-center justify-center hover:border border-transparent hover:border-accent hover:text-accent transition-colors", i === 15 && "bg-accent text-black font-medium")}>{i + 1}</button>\n      ))}\n    </div>\n  </div>\n);\nexport { Calendar };`,

  'DatePicker.jsx': `import React, { useState } from 'react';\nimport { cn } from '../../utils';\nimport { Calendar } from './Calendar';\n\nconst DatePicker = ({ className }) => {\n  const [open, setOpen] = useState(false);\n  return (\n    <div className={cn("relative inline-block", className)}>\n      <button onClick={() => setOpen(!open)} className="border border-border bg-base-800 px-4 py-2 font-mono text-sm text-text-secondary hover:text-accent w-48 text-left">Pick a date...</button>\n      {open && (\n        <div className="absolute top-full left-0 mt-2 z-50 shadow-2xl">\n          <Calendar />\n        </div>\n      )}\n    </div>\n  );\n};\nexport { DatePicker };`,

  'Select.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst Select = React.forwardRef(({ className, options = [], ...props }, ref) => (\n  <select ref={ref} className={cn("flex h-10 w-full items-center justify-between border border-border bg-base-900 px-3 py-2 text-sm placeholder:text-text-secondary focus:outline-none focus:border-accent disabled:cursor-not-allowed disabled:opacity-50 appearance-none rounded-none", className)} {...props}>\n    {options.map((opt, i) => <option key={i} value={opt.value} className="bg-base-900 text-text-primary">{opt.label}</option>)}\n  </select>\n));\nSelect.displayName = "Select";\nexport { Select };`,

  'Command.jsx': `import React from 'react';\nimport { cn } from '../../utils';\nimport { Search } from 'lucide-react';\n\nconst Command = ({ className, ...props }) => (\n  <div className={cn("flex h-full w-full flex-col overflow-hidden bg-base-900 text-text-primary border border-border max-w-lg", className)} {...props}>\n    <div className="flex items-center border-b border-border px-3" cmdk-input-wrapper="">\n      <Search className="mr-2 h-4 w-4 shrink-0 opacity-50" />\n      <input placeholder="Type a command or search..." className="flex h-11 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-text-secondary disabled:cursor-not-allowed disabled:opacity-50" />\n    </div>\n    <div className="max-h-[300px] overflow-y-auto p-2 space-y-1">\n      <div className="px-2 py-1.5 text-xs font-mono uppercase tracking-widest text-text-secondary">Suggestions</div>\n      {['Components', 'Tokens', 'Playground', 'Settings'].map(item => (\n        <div key={item} className="relative flex cursor-pointer select-none items-center px-2 py-1.5 text-sm outline-none hover:bg-base-800 hover:text-accent transition-colors">{item}</div>\n      ))}\n    </div>\n  </div>\n);\nexport { Command };`,

  'Menubar.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst Menubar = ({ className, items, ...props }) => (\n  <div className={cn("flex h-10 items-center space-x-1 border border-border bg-base-900 p-1", className)} {...props}>\n    {items.map(item => (\n      <button key={item} className="cursor-pointer select-none px-3 py-1.5 text-sm font-medium outline-none focus:bg-accent focus:text-accent-foreground hover:bg-base-800 transition-colors">{item}</button>\n    ))}\n  </div>\n);\nexport { Menubar };`,

  'NavigationMenu.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst NavigationMenu = ({ className, links, ...props }) => (\n  <nav className={cn("flex items-center justify-center gap-6 border-b border-border pb-4", className)} {...props}>\n    {links.map(link => (\n      <a key={link} href="#" className="font-mono text-xs uppercase tracking-widest text-text-secondary hover:text-accent transition-colors relative after:absolute after:bottom-[-17px] after:left-0 after:w-full after:h-0.5 after:bg-accent after:opacity-0 hover:after:opacity-100">{link}</a>\n    ))}\n  </nav>\n);\nexport { NavigationMenu };`,

  'Toggle.jsx': `import React, { useState } from 'react';\nimport { cn } from '../../utils';\n\nconst Toggle = React.forwardRef(({ className, defaultPressed = false, children, ...props }, ref) => {\n  const [pressed, setPressed] = useState(defaultPressed);\n  return (\n    <button ref={ref} onClick={() => setPressed(!pressed)} aria-pressed={pressed} className={cn("inline-flex items-center justify-center h-10 px-4 text-sm transition-colors border", pressed ? "bg-base-800 text-accent border-accent" : "bg-transparent text-text-secondary border-transparent hover:bg-base-800 hover:text-text-primary", className)} {...props}>\n      {children}\n    </button>\n  );\n});\nToggle.displayName = "Toggle";\nexport { Toggle };`,

  'ToggleGroup.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst ToggleGroup = ({ className, children, ...props }) => (\n  <div className={cn("flex items-center gap-1 border border-border p-1 bg-base-900 inline-flex", className)} {...props}>\n    {children}\n  </div>\n);\nexport { ToggleGroup };`,

  'AspectRatio.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst AspectRatio = ({ className, ratio = 16/9, children, ...props }) => (\n  <div className={cn("relative w-full", className)} style={{ paddingBottom: \`\${100 / ratio}%\` }} {...props}>\n    <div className="absolute inset-0">\n      {children}\n    </div>\n  </div>\n);\nexport { AspectRatio };`,

  'Collapsible.jsx': `import React, { useState } from 'react';\nimport { cn } from '../../utils';\nimport { motion, AnimatePresence } from 'framer-motion';\n\nconst Collapsible = ({ className, triggerText, children, ...props }) => {\n  const [open, setOpen] = useState(false);\n  return (\n    <div className={cn("border border-border", className)} {...props}>\n      <button onClick={() => setOpen(!open)} className="flex w-full justify-between items-center px-4 py-3 bg-base-800 hover:bg-base-700 transition-colors text-sm font-mono uppercase tracking-widest">\n        {triggerText} <span className="text-accent">{open ? '-' : '+'}</span>\n      </button>\n      <AnimatePresence>\n        {open && (\n          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">\n            <div className="p-4 text-text-secondary text-sm font-light bg-base-900">\n              {children}\n            </div>\n          </motion.div>\n        )}\n      </AnimatePresence>\n    </div>\n  );\n};\nexport { Collapsible };`,

  'Carousel.jsx': `import React, { useState } from 'react';\nimport { cn } from '../../utils';\nimport { ChevronLeft, ChevronRight } from 'lucide-react';\n\nconst Carousel = ({ className, items, ...props }) => {\n  const [index, setIndex] = useState(0);\n  const next = () => setIndex((index + 1) % items.length);\n  const prev = () => setIndex((index - 1 + items.length) % items.length);\n  return (\n    <div className={cn("relative w-full group", className)} {...props}>\n      <div className="overflow-hidden border border-border bg-base-800 aspect-video flex items-center justify-center font-serif text-3xl text-text-secondary">\n        {items[index]}\n      </div>\n      <button onClick={prev} className="absolute left-2 top-1/2 -translate-y-1/2 bg-base-900 border border-border p-2 opacity-0 group-hover:opacity-100 transition-opacity hover:text-accent"><ChevronLeft size={16} /></button>\n      <button onClick={next} className="absolute right-2 top-1/2 -translate-y-1/2 bg-base-900 border border-border p-2 opacity-0 group-hover:opacity-100 transition-opacity hover:text-accent"><ChevronRight size={16} /></button>\n    </div>\n  );\n};\nexport { Carousel };`,

  'ScrollProgress.jsx': `import React from 'react';\nimport { cn } from '../../utils';\nimport { motion, useScroll } from 'framer-motion';\n\nconst ScrollProgress = ({ className, ...props }) => {\n  const { scrollYProgress } = useScroll();\n  return (\n    <motion.div className={cn("fixed top-0 left-0 right-0 h-1 bg-accent z-[100] origin-left", className)} style={{ scaleX: scrollYProgress }} {...props} />\n  );\n};\nexport { ScrollProgress };`,

  'CustomCursor.jsx': `import React, { useEffect, useState } from 'react';\nimport { motion } from 'framer-motion';\n\nconst CustomCursor = () => {\n  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });\n  useEffect(() => {\n    const update = (e) => setMousePosition({ x: e.clientX, y: e.clientY });\n    window.addEventListener('mousemove', update);\n    return () => window.removeEventListener('mousemove', update);\n  }, []);\n  return (\n    <motion.div animate={{ x: mousePosition.x - 16, y: mousePosition.y - 16 }} transition={{ type: "tween", ease: "backOut", duration: 0.15 }} className="fixed top-0 left-0 w-8 h-8 rounded-full border border-accent pointer-events-none z-[999] hidden md:block" />\n  );\n};\nexport { CustomCursor };`,

  'ImageReveal.jsx': `import React from 'react';\nimport { cn } from '../../utils';\nimport { motion } from 'framer-motion';\n\nconst ImageReveal = ({ className, src, alt, ...props }) => (\n  <div className={cn("relative overflow-hidden group border border-border", className)} {...props}>\n    <div className="absolute inset-0 bg-base-900 z-10 transition-transform duration-700 ease-[cubic-bezier(0.77,0,0.175,1)] group-hover:-translate-y-full origin-top" />\n    <img src={src} alt={alt} className="w-full h-full object-cover" />\n  </div>\n);\nexport { ImageReveal };`,

  'KineticText.jsx': `import React from 'react';\nimport { cn } from '../../utils';\nimport { motion } from 'framer-motion';\n\nconst KineticText = ({ className, text, ...props }) => {\n  const letters = Array.from(text);\n  return (\n    <div className={cn("flex overflow-hidden font-serif", className)} {...props}>\n      {letters.map((letter, i) => (\n        <motion.span key={i} initial={{ y: "100%" }} whileInView={{ y: 0 }} transition={{ duration: 0.5, delay: i * 0.05, ease: [0.2, 0.65, 0.3, 0.9] }} viewport={{ once: true }}>\n          {letter === ' ' ? '\\u00A0' : letter}\n        </motion.span>\n      ))}\n    </div>\n  );\n};\nexport { KineticText };`,

  'ContextMenu.jsx': `import React from 'react';\nimport { cn } from '../../utils';\n\nconst ContextMenu = ({ className, children, trigger, ...props }) => (\n  <div className={cn("relative group inline-block", className)} {...props}>\n    {trigger}\n    <div className="absolute left-1/2 top-1/2 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-opacity z-50 bg-base-900 border border-border min-w-[150px] p-1 shadow-2xl">\n      <div className="px-3 py-1 font-mono text-[10px] uppercase text-text-secondary border-b border-border mb-1">Context Options</div>\n      {children}\n    </div>\n  </div>\n);\nexport { ContextMenu };`
};

Object.entries(files).forEach(([name, content]) => {
  fs.writeFileSync(path.join(dir, name), content);
  console.log('Created ' + name);
});
